title:             Julien Liabeuf
description:       Thoughts and opinions on tech, web, and products.
tagline:           Product Manager and Problem Solver

url:               https://julienliabeuf.com
baseurl:           ""
paginate_path:     "blog/page/:num/"
permalink:         :title/

repository:        julien731/blog-jekyll

# Staticman comments (full configuration in staticman.yml)
staticman:
  branch:          "master"

collections:
  work:
    output:        true
    permalink:     /:collection/:name

defaults:
- scope:
    path:          ""
    type:          work
  values:
    layout:        work

markdown:          kramdown
highlighter:       rouge
plugins:           [jekyll-paginate]
paginate:          5

navigation:
 - title:          Home
   url:            /
 - title:          About
   url:            /about
 - title:          Contact
   url:            /contact

author:
  name:            Julien Liabeuf

social:
   github:         julien731
   twitter:        julien731
   email:          julien@liabeuf.fr
   googleplus:     +JulienLiabeuf

google_analytics:  "G-8L5KEN74L9"

exclude:
  - .github/
  - .idea/
  - bin/
  - node_modules/
  - resources/
  - vendor/
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - package.json
  - package-lock.json
  - README.md
  - docker-compose.dev.yml
  - gulpfile.js